name: Build and deploy Node.js app to Azure Web App - travel-planner-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install all dependencies
        run: npm install --include=dev

      - name: Build frontend
        run: npm run build
        env:
          CI: false

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'travel-planner-app'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_00D11D44CA7E4DF6980186AEBEF001CC }}
